Author.delete_all
ck = Author.create(:name => "Christina Baker Kline")
nr = Author.create(:name => "Nora Roberts")
pc = Author.create(:name => "Paulo Coelho")
db = Author.create(:name => "David Baldacci")
gm = Author.create(:name => "George R R Martin")
ca = Author.create(:name => "Chimamanda Ngozi Adichie")
jm = Author.create(:name => "Jojo Moyes")
es = Author.create(:name => "Elizabeth Strout")
mw = Author.create(:name => "Meg Wolitzer")
kh = Author.create(:name => "Kristin Hannah")
jw = Author.create(:name => "Jess Walter")
ms = Author.create(:name => "M L Stedman")
ro = Author.create(:name => "Ruth Ozeki")
er = Author.create(:name => "Edward Rutherfurd")
eh = Author.create(:name => "Elin Hilderbrand")
gf = Author.create(:name => "Gillian Flynn")
rc = Author.create(:name => "Ron Carr")
pg = Author.create(:name => "Philippa Gregory")

Book.delete_all
orphan = Book.create(:title => "Orphan Train", :author_id => ck.id, :price => 26)
shadow = Book.create(:title => "Shadow Spell", :author_id => nr.id, :price => 15)
alchemist = Book.create(:title => "The Alchemist", :author_id => pc.id, :price => 12)
king = Book.create(:title => "King And Maxwell", :author_id => db.id, :price => 35)
whiskey = Book.create(:title => "Whiskey Beach", :author_id => nr.id, :price => 22)
game = Book.create(:title => "A Game Of Thrones", :author_id => gm.id, :price => 24)
americanah = Book.create(:title => "Americanah", :author_id => ca.id, :price => 20)
me = Book.create(:title => "Me Before You", :author_id => jm.id, :price => 18)
burgess = Book.create(:title => "The Burgess Boys", :author_id => es.id, :price => 15)
interestings = Book.create(:title => "The Interestings", :author_id => mw.id, :price => 27)
fly = Book.create(:title => "Fly Away", :author_id => kh.id, :price => 23)
beautiful = Book.create(:title => "Beautiful Ruins", :author_id => jw.id, :price => 14)
light = Book.create(:title => "The Light Between Oceans", :author_id => ms.id, :price => 25)
tale = Book.create(:title => "A Tale For The Time Being", :author_id => ro.id, :price => 34)
paris = Book.create(:title => "Paris", :author_id => er.id, :price => 38)
day = Book.create(:title => "Beautiful Day", :author_id => eh.id, :price => 16)
dark = Book.create(:title => "Dark Places", :author_id => gf.id, :price => 15)
four = Book.create(:title => "Four Friends", :author_id => rc.id, :price => 20)
white = Book.create(:title => "The White Princess", :author_id => pg.id, :price => 24)

Review.delete_all
Review.create(:book_id => orphan.id, :stars => 5, :review => "Riveting!")
Review.create(:book_id => orphan.id, :stars => 2, :review => "About as dull as you can get.")
Review.create(:book_id => orphan.id, :stars => 3, :review => "Not bad.")
Review.create(:book_id => shadow.id, :stars => 4, :review => "Great book, and not too many pages.")
Review.create(:book_id => shadow.id, :stars => 4, :review => "Excellent font and margins.  Story wasn't bad, either.")
Review.create(:book_id => shadow.id, :stars => 4, :review => "Worth reading when there isn't a hockey game on.")
Review.create(:book_id => shadow.id, :stars => 1, :review => "Didn't understand it at all.")
Review.create(:book_id => alchemist.id, :stars => 2, :review => "I thought this was about how to make gold?")
Review.create(:book_id => alchemist.id, :stars => 4, :review => "Suspensful plot, good characters.")
Review.create(:book_id => alchemist.id, :stars => 5, :review => "Perfect.  A work of art.")
Review.create(:book_id => alchemist.id, :stars => 3, :review => "Kind of confusing.")# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
